# Generated by Django 4.1.3 on 2022-12-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('text', models.TextField()),
                ('finish', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.newsletter')),
            ],
        ),
    ]
