# Generated by Django 4.1.3 on 2022-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_timezone'),
        ('api', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='filter', to='clients.client'),
        ),
    ]
